# Bioconda recipes explorer

#### Imports

In [1]:
import json
import plotly
import pandas as pd

from pymongo import MongoClient
import plotly.io as pio
from bunch import bunchify
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from collections import Counter
 
plotly.io.orca.config.executable = '/path/to/orca'
plotly.io.orca.config.save()

#### Connection to DB

In [8]:
client = MongoClient(port=27017)
db = client.FAIRsoft
alambique_coll = db.alambique
pretools_coll = db.pretools

#### Retrieval of tools

In [3]:
def describe_collection(source):
    tools = []
    columns = set()
    for tool in alambique_coll.find({'@data_source':source}):
        [columns.add(col) for col in tool.keys()]
        tools.append(tool)

    tool_df = pd.DataFrame(tools, columns=columns)  
    tool_df.describe()

In [ ]:
describe_collection('bioconda')

In [11]:
def describe_collection_pretools(source):
    tools = []
    columns = set()
    for tool in pretools_coll.find({'source':[source]}):
        [columns.add(col) for col in tool.keys()]
        tools.append(tool)

    tool_df = pd.DataFrame(tools, columns=columns)  
    tool_df.describe()
    return(tool_df.describe())

In [12]:
describe_collection_pretools('bioconda_recipes')

,output,semantics,name,license,download,contribPolicy,termsUse,links,dependencies,os,...,edam_topics,inst_instr,ssl,operational,type,repository,documentation,input,https,description
count,8910,8910,8910,8910,8910,8910,8910,8910,8910,8910,...,8910,8910,0,0,8910,8910,8910,8910,0,8910
unique,1,1,7953,505,7853,1,505,7972,5777,1,...,1,1,0,0,2,3108,313,1,0,3627
top,[],{},diamond,[MIT],[http://hgdownload.cse.ucsc.edu/admin/exe/user...,False,[MIT],"[http://hgdownload.cse.ucsc.edu/admin/exe/, ht...","[bioconductor-annotationdbi >=1.56.0,<1.57.0, ...","[Linux, Mac, Windows]",...,[],True,NaN,NaN,lib,[],[],[],NaN,[]
freq,8910,8910,13,1268,249,8910,1268,249,266,8910,...,8910,8910,NaN,NaN,5110,5020,8420,8910,NaN,5149

In [13]:
describe_collection_pretools('bioconda')

,output,semantics,name,license,download,contribPolicy,termsUse,links,dependencies,os,...,edam_topics,inst_instr,ssl,operational,type,repository,documentation,input,https,description
count,54524,54524,54524,54524,54524,54524,54524,54524,54524,54524,...,54524,54524,54524,54524,54524,54524,54524,54524,54524,54524
unique,1,1,9483,597,44048,1,1,25253,1,1,...,1,1,1,1,2,150,1,1,1,11748
top,[],{},diamond,[MIT],[https://anaconda.org/bioconda/entrez-direct/5...,False,[],"[http://hgdownload.cse.ucsc.edu/admin/exe/, ht...",[],[],...,[],False,False,False,lib,[],[],[],False,[Accelerated BLAST compatible local sequence a...
freq,54524,54524,520,8307,16,54524,54524,1063,54524,54524,...,54524,54524,54524,54524,30477,54181,54524,54524,54524,520